config:
  openai:
    api_key: "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    models:
      gpt-3.5:
        name: "gpt-3.5-turbo"
        cost_per_1k_tokens: 0.002
        max_tokens: 4096
        enabled: true
      gpt-4:
        name: "gpt-4"
        cost_per_1k_tokens: 0.03
        max_tokens: 8192
        enabled: true
      gpt-4-32k:
        name: "gpt-4-32k"
        cost_per_1k_tokens: 0.06
        max_tokens: 32768
        enabled: true

  translator:
    api:
      terms_list:
        models: 
          - gpt-3.5
      translation:
        models:
          - gpt-3.5
      summary:
        models:
          - gpt-3.5
      metadata:
        models:
          - gpt-3.5
    target_language: "en"

  languages:
    - en: "English"
    - de: "German"
    - es: "Spanish"
    - fr: "French"
    - it: "Italian"
    - ja: "Japanese"
    - ko: "Korean"
    - nl: "Dutch"
    - pt: "Portuguese"
    - ru: "Russian"
    - zh: "Chinese"

  spacy:
    pipelines:
      - en: "en_core_web_sm"
      - de: "de_core_news_sm"
      - es: "es_core_news_sm"
      - fr: "fr_core_news_sm"
      - it: "it_core_news_sm"
      - ja: "ja_core_news_sm"
      - ko: "ko_core_news_sm"
      - nl: "nl_core_news_sm"
      - pt: "pt_core_news_sm"
      - ru: "ru_core_news_sm"
      - zh: "zh_core_web_sm"
      