config:
  openai:
    api_key: "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    models:
      gpt-3.5:
        name: "gpt-3.5-turbo"
        cost_per_1k_tokens: 0.002
        max_tokens: 4096
        enabled: true
      gpt-4:
        name: "gpt-4"
        cost_per_1k_tokens: 0.03
        max_tokens: 8192
        enabled: true
      gpt-4-32k:
        name: "gpt-4-32k"
        cost_per_1k_tokens: 0.06
        max_tokens: 32768
        enabled: true

  translator:
    api:
      terms_list:
        models: 
          - gpt-4
      translation:
        models:
          - gpt-3.5
          - gpt-4
      summary:
        models:
          - gpt-3.5
          - gpt-4
      metadata:
        models:
          - gpt-4